### ISSUE TITLE
Crypto HMAC Error

### ISSUE THREAD

**Issue by NullDev** [savetheinternetinfo/autoupdater#1]
This line here throws an error because the argument is not a buffer. Data however is returned from `bl()`.

https://github.com/savetheinternetinfo/autoupdater/blob/6bda9900fd3107baf87c2b21ce6ca6881baba425/src/utils/verifyRequest.js#L18

Buffer from req body is returned here:

https://github.com/savetheinternetinfo/autoupdater/blob/6bda9900fd3107baf87c2b21ce6ca6881baba425/src/utils/verifyRequest.js#L33-L45

**Comment by NullDev** [comment]
Fixed. 
Buffer wasn't even needed. Error message was misleading. The argument can be a string as well. 

Here was the complete error message:

```ASM
TypeError: Key must be a buffer
    at new Hmac (crypto.js:117:16)
    at Object.createHmac (crypto.js:643:10)
    at signData (/var/www/tests/autoupdater/src/utils/verifyRequest.js:18:27)
    at verifySignature (/var/www/tests/autoupdater/src/utils/verifyRequest.js:30:55)
    at verifyRequest (/var/www/tests/autoupdater/src/utils/verifyRequest.js:63:10)
    at app.post (/var/www/tests/autoupdater/src/hooks.js:70:24)
    at Layer.handle [as handle_request] (/var/www/tests/autoupdater/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/tests/autoupdater/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/tests/autoupdater/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/tests/autoupdater/node_modules/express/lib/router/layer.js:95:5)

```
